export const ActionType = {
	GET_SUGGESTED_USER: 'GET_SUGGESTED_USER',
	GET_CURRENT_USER: 'GET_CURRENT_USER',
	CREATE_NEW_POST: 'CREATE_NEW_POST',
	GET_CONTACT_USER: 'GET_CONTACT_USER',
	ADD_FRIEND: 'ADD_FRIEND',
	GET_ALL_POST: 'GET_ALL_POST',
};
